# Generated by Django 5.2.13 on 2026-04-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=200)),
                ('feature', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('MEETING', 'Meeting'), ('RESEARCH', 'Research'), ('TESTING', 'Testing'), ('DOCUMENTATION', 'Documentation'), ('MAINTENANCE', 'Maintenance'), ('DEPLOYMENT', 'Deployment'), ('CODE_REVIEW', 'Code Review'), ('TRAINING', 'Training'), ('OTHER', 'Other')], max_length=30)),
                ('work_description', models.TextField()),
                ('duration', models.DurationField()),
                ('work_mode', models.CharField(choices=[('OFFICE', 'Office'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='attendance/photos/')),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='attendance/photos/')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('ON_LEAVE', 'On Leave')], default='ABSENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-check_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
