# Generated by Django 5.2.13 on 2026-04-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_chatbotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='IT Org', max_length=200)),
                ('organization_short_name', models.CharField(default='IT Org', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('primary_color', models.CharField(default='#FF6B00', max_length=7)),
                ('secondary_color', models.CharField(default='#0B1F3A', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
    ]
