# Generated by Django 5.2.13 on 2026-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_organization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, default='', help_text='URL for meeting (Google Meet, Zoom, etc.)', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('TRAINING', 'Training'), ('EVENT', 'Company Event'), ('HOLIDAY', 'Holiday'), ('OTHER', 'Other')], default='MEETING', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
