# Generated by Django 5.2.13 on 2026-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_add_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', help_text='Auto-updated based on time', max_length=20),
        ),
    ]
