# Generated by Django 5.2.13 on 2026-04-24 13:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_add_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowance_hra', models.DecimalField(decimal_places=2, default=0, help_text='House Rent Allowance', max_digits=10)),
                ('allowance_conveyance', models.DecimalField(decimal_places=2, default=0, help_text='Conveyance Allowance', max_digits=10)),
                ('allowance_medical', models.DecimalField(decimal_places=2, default=0, help_text='Medical Allowance', max_digits=10)),
                ('allowance_special', models.DecimalField(decimal_places=2, default=0, help_text='Special Allowance', max_digits=10)),
                ('allowance_other', models.DecimalField(decimal_places=2, default=0, help_text='Other Allowances', max_digits=10)),
                ('deduction_tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax Deduction (TDS)', max_digits=10)),
                ('deduction_insurance', models.DecimalField(decimal_places=2, default=0, help_text='Insurance', max_digits=10)),
                ('deduction_other', models.DecimalField(decimal_places=2, default=0, help_text='Other Deductions', max_digits=10)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
