# Generated by Django 5.2.13 on 2026-04-18 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('EXECUTIVE', 'Executive Leadership'), ('UPPER_MANAGEMENT', 'Upper Management'), ('MIDDLE_MANAGEMENT', 'Middle Management'), ('SENIOR_PROFESSIONAL', 'Senior Professional'), ('JUNIOR_PROFESSIONAL', 'Junior Professional'), ('SUPPORT', 'Support Function')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='departments.department')),
            ],
            options={
                'ordering': ['level', 'title'],
                'unique_together': {('title', 'department')},
            },
        ),
    ]
